//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zhaobang.Xspf {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zhaobang.Xspf.ErrorMessages", typeof(ErrorMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 There is not enough space in the array. 的本地化字符串。
        /// </summary>
        internal static string ArrayDoesNotFit {
            get {
                return ResourceManager.GetString("ArrayDoesNotFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element {0} is expected in {1} but it is not found. 的本地化字符串。
        /// </summary>
        internal static string ElementMissing {
            get {
                return ResourceManager.GetString("ElementMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of element {0} is not legal date. 的本地化字符串。
        /// </summary>
        internal static string ElementNotLegalDate {
            get {
                return ResourceManager.GetString("ElementNotLegalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of element {0} is not legal URI. 的本地化字符串。
        /// </summary>
        internal static string ElementNotLegalUri {
            get {
                return ResourceManager.GetString("ElementNotLegalUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element name is expected to be {0}, but it is actually {1}. 的本地化字符串。
        /// </summary>
        internal static string WrongElementName {
            get {
                return ResourceManager.GetString("WrongElementName", resourceCulture);
            }
        }
    }
}
